# Generated by Django 5.2.1 on 2025-06-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_customuser_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["last_name", "first_name"],
                "permissions": [("can_block_user", "Can block and unblock")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
    ]
