# Generated by Django 5.2.1 on 2025-06-09 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["last_name", "first_name"],
                "permissions": [("can_block_user", "Can block and unblock users")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
        migrations.CreateModel(
            name="UsersControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        to=settings.AUTH_USER_MODEL, verbose_name="Пользователи"
                    ),
                ),
            ],
            options={
                "verbose_name": "Управление пользователями",
            },
        ),
    ]
