# Generated by Django 5.2.1 on 2025-06-09 08:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_options_userscontrol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userscontrol",
            name="users",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователи, которым можно заходить в приложение",
            ),
        ),
    ]
