# Generated by Django 5.2.1 on 2025-05-30 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sender", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ["full_name"]},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["updated_at", "topic"]},
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "send_start",
                    models.DateTimeField(
                        blank=True, verbose_name="Дата и время первой отправки"
                    ),
                ),
                (
                    "send_stop",
                    models.DateTimeField(
                        blank=True, verbose_name="Дата и время окончания отправки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="Создана", max_length=9, verbose_name="Тема"
                    ),
                ),
                ("clients", models.ManyToManyField(to="sender.client")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailings",
                        to="sender.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
        ),
    ]
