# Generated by Django 5.2.1 on 2025-06-05 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sender", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время попытки рассылки"
                    ),
                ),
                (
                    "is_successful",
                    models.BooleanField(default=False, verbose_name="Статус попытки"),
                ),
                (
                    "server_response",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="Ответ сервера"
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="sender.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
        ),
    ]
