# Generated by Django 5.2.1 on 2025-06-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sender", "0002_alter_client_options_alter_message_options_mailing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="mailing",
            name="send_start",
            field=models.DateTimeField(verbose_name="Дата и время первой отправки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="send_stop",
            field=models.DateTimeField(verbose_name="Дата и время окончания отправки"),
        ),
    ]
