# Generated by Django 5.2.1 on 2025-06-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sender", "0002_alter_client_owner_alter_mailing_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="message",
            name="owner",
        ),
    ]
