# Generated by Django 5.2.1 on 2025-06-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sender", "0003_alter_mailing_options_alter_mailing_send_start_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(to="sender.client", verbose_name="Клиенты"),
        ),
    ]
