# Generated by Django 5.2.1 on 2025-06-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sender", "0008_alter_mailing_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attempt",
            options={
                "ordering": ["-id"],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "попытки рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["full_name"],
                "verbose_name": "Клиент",
                "verbose_name_plural": "клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["-id"],
                "permissions": [
                    ("can_disable_mailing", "Can enable and disable mailing")
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["updated_at", "topic"],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
    ]
