# Generated by Django 5.2.1 on 2025-06-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sender", "0009_alter_attempt_options_alter_client_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="enabled",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
    ]
