# Generated by Django 5.2.1 on 2025-06-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sender", "0011_attempt_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
