# Generated by Django 5.2.1 on 2025-06-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sender", "0012_alter_client_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="scheduler_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Автовыполнение активно"
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="scheduler_interval",
            field=models.CharField(
                default="1d", max_length=20, verbose_name="Интервал автовыполнения"
            ),
        ),
    ]
