# Generated by Django 5.2.1 on 2025-06-11 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sender", "0013_mailing_scheduler_enabled_mailing_scheduler_interval"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="scheduler_interval",
        ),
        migrations.AddField(
            model_name="mailing",
            name="scheduler_days_interval",
            field=models.IntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Интервал в днях",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="scheduler_hours_interval",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Интервал в часах",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="scheduler_minutes_interval",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Интервал в минутах",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="scheduler_seconds_interval",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Интервал в секундах",
            ),
        ),
    ]
