CREATE ROLE hhuser WITH LOGIN SUPERUSER CREATEDB CREATEROLE INHERIT NOREPLICATION BYPASSRLS CONNECTION LIMIT -1
PASSWORD '123456';

CREATE DATABASE massmail WITH OWNER = hhuser ENCODING = 'UTF8' CONNECTION LIMIT = -1 IS_TEMPLATE = False;