from django.urls import path
from . import views

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("new_client/", views.ClientCreateView.as_view(), name="new_client"),
    path("client_details/<int:pk>/", views.ClientDetailView.as_view(), name="client_details"),
    path("edit_client/<int:pk>/", views.ClientUpdateView.as_view(), name="edit_client"),
    path("delete_client/<int:pk>/", views.ClientDeleteView.as_view(), name="delete_client"),
    path("clients_list/", views.ClientListView.as_view(), name="clients_list", kwargs={"model": "Client",
                                                                                       "show_all": False}),
    path("all_clients_list/", views.ClientListView.as_view(), name="all_clients_list", kwargs={"model": "Client",
                                                                                               "show_all": True}),
    path("new_message/", views.MessageCreateView.as_view(), name="new_message"),
    path("message_details/<int:pk>/", views.MessageDetailView.as_view(), name="message_details"),
    path("edit_message/<int:pk>/", views.MessageUpdateView.as_view(), name="edit_message"),
    path("delete_message/<int:pk>/", views.MessageDeleteView.as_view(), name="delete_message"),
    path("messages_list/", views.MessageListView.as_view(), name="messages_list"),
    path("new_mailing/", views.MailingCreateView.as_view(), name="new_mailing"),
    path("mailing_details/<int:pk>/", views.MailingDetailView.as_view(), name="mailing_details"),
    path("edit_mailing/<int:pk>/", views.MailingUpdateView.as_view(), name="edit_mailing"),
    path("delete_mailing/<int:pk>/", views.MailingDeleteView.as_view(), name="delete_mailing"),
    path("force_mailing/<int:pk>/", views.ForceSendMailingView.as_view(), name="force_mailing"),
    path("delete_mailing/<int:pk>/", views.MailingDeleteView.as_view(), name="delete_mailing"),
    path("copy_mailing/<int:pk>/", views.CopyMailingView.as_view(), name="copy_mailing"),
    path("mailing_list/", views.MailingListView.as_view(), name="mailing_list", kwargs={"model": "Mailing",
                                                                                        "show_all": False}),
    path("all_mailing_list/", views.MailingListView.as_view(), name="all_mailing_list", kwargs={"model": "Mailing",
                                                                                                "show_all": True}),
    path("attempts_list/", views.AttemptListView.as_view(), name="attempts_list", kwargs={"model": "Attempt",
                                                                                          "show_all": False}),
    path("all_attempts_list/", views.AttemptListView.as_view(), name="all_attempts_list", kwargs={"model": "Attempt",
                                                                                                  "show_all": True}),
    path("disable_mailing/<int:pk>/", views.MailingDetailView.as_view(), name="disable_mailing",
         kwargs={"model": "Mailing",
                 "disable": True}),
    path("mailing_attempts/<int:pk>/", views.MailingAttemptsListView.as_view(), name="mailing_attempts"),
    path("errors/", views.MailingErrorsView.as_view(), name="errors"),
    path("statistics/", views.StatisticsView.as_view(), name="statistics"),
]
